// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChangeStoreTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changeStore() {
    driver.get("https://www.homedepot.ca/en/home.html");
    driver.manage().window().setSize(new Dimension(1184, 1222));
    driver.findElement(By.cssSelector(".acl-store-hours-menu__chevron > svg")).click();
    driver.findElement(By.cssSelector(".acl-m--small:nth-child(1)")).click();
    assertThat(driver.findElement(By.linkText("Change Store")).getText(), is("Change Store"));
    driver.findElement(By.linkText("Change Store")).click();
    driver.findElement(By.id("default")).click();
    driver.findElement(By.id("default")).sendKeys("toronto");
    driver.findElement(By.cssSelector(".hdca-input-group__action-button-icon > svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".hdca-input-group__action-button-icon > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".hdca-store-list-item:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".hdca-store-list-item:nth-child(1) .hdca-store__address")).getText(), is("1000 Gerrard Street East, Toronto, ON, M4M 3G6"));
    driver.findElement(By.cssSelector(".hdca-store-list-item:nth-child(1) .acl-button--theme--primary")).click();
    driver.findElement(By.cssSelector(".acl-store-hours-menu__chevron")).click();
    driver.findElement(By.cssSelector(".acl-dropdown__menu > .ng-tns-c58-2:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".acl-store-info__title")).getText(), is("GERRARD SQUARE"));
  }
}
