// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FindHomeServicesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void findHomeServices() {
    driver.get("https://www.homedepot.ca/en/home.html");
    driver.manage().window().setSize(new Dimension(1491, 1269));
    driver.findElement(By.cssSelector("#InstallationServicesMainNavNodeContainer .acl-main-nav-item__label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#InstallationServicesMainNavNodeContainer .acl-main-nav-item__label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".acl-breadcrumbs__link > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("sc-navigator")).click();
    assertThat(driver.findElement(By.cssSelector(".acl-breadcrumbs__link > span")).getText(), is("Home"));
    driver.findElement(By.cssSelector(".hdca-service-connect-accordion:nth-child(2) > .hdca-service-connect-accordion__last-child:nth-child(5) .hdca-service-connect-accordion__title-text")).click();
    driver.findElement(By.linkText("Cabinet Refacing")).click();
    driver.findElement(By.cssSelector(".hdca-cms-home-services-banner__wrapper-content--text")).click();
    driver.findElement(By.cssSelector(".hdca-cms-home-services-banner__wrapper-content--text-rating")).click();
    js.executeScript("window.scrollTo(0,2362)");
    driver.findElement(By.cssSelector(".hdca-cms-home-services-banner__wrapper-content")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".hdca-cms-home-services-banner__wrapper-content--text-title"));
      assert(elements.size() > 0);
    }
  }
}
