// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavigateToProductReviewsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigateToProductReviews() {
    driver.get("https://www.homedepot.ca/en/home.html");
    driver.manage().window().setSize(new Dimension(1752, 1110));
    js.executeScript("window.scrollTo(0,150)");
    driver.findElement(By.cssSelector(".hdca-cms-category-banner-container__list-item--4 .hdca-cms-category-banner__image")).click();
    driver.findElement(By.cssSelector(".styledlayoutcontainer:nth-child(12) .hdca-cms-secondary-banner__image")).click();
    js.executeScript("window.scrollTo(0,1821)");
    js.executeScript("window.scrollTo(0,1478)");
    driver.findElement(By.cssSelector(".categorybanner:nth-child(1) .hdca-button2__non-wrap-label")).click();
    js.executeScript("window.scrollTo(0,222)");
    {
      WebElement element = driver.findElement(By.cssSelector(".acl-product-card:nth-child(2) .acl-rating__reviews"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".acl-product-card:nth-child(2) .acl-rating__reviews")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,10)");
    js.executeScript("window.scrollTo(0,3260)");
    js.executeScript("window.scrollTo(0,3545)");
    driver.findElement(By.cssSelector(".product-reviews-title")).click();
    assertThat(driver.findElement(By.cssSelector(".product-reviews-title")).getText(), is("Customer Reviews"));
  }
}
