// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchValidWeeklyFlyerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchValidWeeklyFlyer() {
    driver.get("https://www.homedepot.ca/en/home.html");
    driver.manage().window().setSize(new Dimension(1166, 1290));
    driver.findElement(By.cssSelector("#navnode_000003UXContainer .acl-main-nav-item__label")).click();
    driver.findElement(By.cssSelector(".hdca-weekly-flyer__wrapper")).click();
    assertThat(driver.findElement(By.cssSelector(".acl-breadcrumbs__link > span")).getText(), is("Home"));
    driver.switchTo().frame(3);
    driver.findElement(By.cssSelector(".flipp-navbar-menu-button-icon-span > img")).click();
    driver.switchTo().defaultContent();
    driver.switchTo().frame(5);
    driver.findElement(By.id("search-keywords")).click();
    driver.findElement(By.id("search-keywords")).sendKeys("paint");
    driver.findElement(By.cssSelector(".form-icon-search svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".form-icon-search svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".form-icon-search path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".list-wrapper")).click();
    assertThat(driver.findElement(By.id("search-view-details-button-763402253")).getText(), is("View details"));
  }
}
