// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchItemTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchItem() {
    driver.get("https://www.homedepot.ca/en/home.html");
    driver.findElement(By.id("id8451")).click();
    driver.findElement(By.id("id8451")).sendKeys("Milwaukee Tool PACKOUT 22-inch Rolling Tool Box");
    driver.findElement(By.id("id8451")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".acl-product-card:nth-child(1) .acl-image__image")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".hdca-product__description-jump-menu-item .acl-rating__stars-overlay"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".hdca-product")).click();
    assertThat(driver.findElement(By.cssSelector(".hdca-product__description-title-product-name")).getText(), is("PACKOUT 22-inch Rolling Tool Box"));
    driver.manage().window().setSize(new Dimension(1752, 1110));
  }
}
