// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignInInvalidTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signInInvalid() {
    driver.get("https://www.homedepot.ca/myaccount");
    driver.manage().window().setSize(new Dimension(1166, 1290));
    driver.findElement(By.cssSelector(".lg\\3A acl-col--5:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".acl-col--12:nth-child(1) > div > .acl-mt--medium")).getText(), is("Sign In"));
    driver.findElement(By.id("login.emailAddress")).click();
    driver.findElement(By.id("login.emailAddress")).sendKeys("jd121212@gmail.com");
    driver.findElement(By.id("login.password")).click();
    driver.findElement(By.id("login.password")).sendKeys("software69420");
    driver.findElement(By.cssSelector(".acl-button--theme--primary:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".hdca-alert__message")).click();
    assertThat(driver.findElement(By.cssSelector(".hdca-alert__message")).getText(), is("Please confirm the email address entered is correct. If it is, click Forgot Password to reset the password on your account. If you are still unable to log in, please contact us."));
  }
}
