// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VerifyProductReviewsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void verifyProductReviews() {
    driver.get("https://www.homedepot.ca/en/home.html");
    driver.manage().window().setSize(new Dimension(1710, 1188));
    driver.findElement(By.cssSelector(".hdca-cms-category-banner-container__list-item--5 .hdca-cms-category-banner__image")).click();
    js.executeScript("window.scrollTo(0,791)");
    driver.findElement(By.cssSelector(".styledlayoutcontainer:nth-child(7) .hdca-cms-category-banner__image")).click();
    js.executeScript("window.scrollTo(0,142)");
    js.executeScript("window.scrollTo(0,673)");
    js.executeScript("window.scrollTo(0,707)");
    driver.findElement(By.cssSelector(".categorybanner:nth-child(5) .hdca-cms-category-banner__image")).click();
    js.executeScript("window.scrollTo(0,356)");
    driver.findElement(By.cssSelector(".acl-product-card:nth-child(2) .acl-rating__reviews")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,997)");
    js.executeScript("window.scrollTo(0,2907)");
    js.executeScript("window.scrollTo(0,3741)");
    driver.findElement(By.cssSelector(".hdca-product__description-title")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".hdca-product__description-title-product-name"));
      assert(elements.size() > 0);
    }
  }
}
